---
apiVersion: v1
kind: Secret
metadata:
  name: hpg-01-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-gh/hpg-01-gateway-gitops
